---
- name: Configure Apache
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
    
    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes
    
    - name: Copy HTML file
      copy:
        src: /vagrant/Index.html
        dest: /var/www/html/index.html

